// Downloads the official Ko-fi widget PNG and embeds it as a base64 data URL
// in `src/kofi-asset.ts`. Wired as a prebuild hook so the asset is regenerated
// alongside the icons. Idempotent - skips the fetch when the generated file
// already exists.
//
// We bake the image into the bundle (rather than loading it from
// storage.ko-fi.com at runtime) because Strava's content-script CSP blocks
// third-party `img-src`, and because a data URL keeps the extension working
// fully offline.

import { stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const src = 'https://storage.ko-fi.com/cdn/kofi6.png?v=6';
const dst = path.join(root, 'src', 'kofi-asset.ts');

// The real Ko-fi PNG produces a file roughly 11 KB after base64-encoding plus
// the TS wrapper. Anything under this threshold is either the previous
// 1×1 transparent fallback or the inline-SVG approximation that ships when
// the build ran without network access. In either case we want to attempt
// a refetch so the toolbar shows the official button - but if the refetch
// itself fails (offline build, sandboxed CI, etc.) we keep the placeholder
// so the build doesn't error.
const PLACEHOLDER_THRESHOLD_BYTES = 4_000;
let hasPlaceholder = false;

try {
	const info = await stat(dst);
	if (info.size >= PLACEHOLDER_THRESHOLD_BYTES) {
		console.log('kofi-asset.ts already present - skipping (delete to refetch).');
		process.exit(0);
	}
	hasPlaceholder = true;
	console.log(`kofi-asset.ts is a ${info.size}-byte placeholder - refetching real artwork...`);
} catch {
	/* no existing file - fall through to download */
}

console.log(`fetching ${src} ...`);
let res;
try {
	res = await fetch(src);
} catch (err) {
	if (hasPlaceholder) {
		// Network is unreachable, but we already have an SVG approximation on
		// disk. Keep it; the next build that has network access will replace
		// it with the real PNG.
		console.warn(`Ko-fi asset fetch failed (${err.code ?? err.message}); keeping existing placeholder.`);
		process.exit(0);
	}
	console.error(`Ko-fi asset fetch failed: ${err.code ?? err.message}`);
	process.exit(1);
}
if (!res.ok) {
	if (hasPlaceholder) {
		console.warn(`Ko-fi asset fetch returned HTTP ${res.status}; keeping existing placeholder.`);
		process.exit(0);
	}
	console.error(`Ko-fi asset fetch failed: HTTP ${res.status}`);
	process.exit(1);
}
const bytes = Buffer.from(await res.arrayBuffer());
const dataUrl = `data:image/png;base64,${bytes.toString('base64')}`;
const contents =
	'// Auto-generated by scripts/build-kofi.js. Do not edit.\n' +
	`export const KOFI_IMAGE: string = ${JSON.stringify(dataUrl)};\n`;
await writeFile(dst, contents);
console.log(`wrote ${dst} (${bytes.length} bytes → ${dataUrl.length} char data URL)`);
